#!/bin/sh 
### BEGIN INIT INFO 
# Provides:          ss-servers
# Required-Start:    $network $local_fs $remote_fs $syslog 
# Required-Stop:     $remote_fs 
# Default-Start:     2 3 4 5 
# Default-Stop:      0 1 6 
# Short-Description: Start ss-servers at boot time 
### END INIT INFO 
### Begin Deploy Path 
# Put this file at /etc/init.d/ 
### End Deploy Path 
DAEMON=/usr/bin/ss-server
CONFDIR=/home/neozero/ss-server-conf/conf
DESC=ss-servers
NAME=ss-servers
PIDFILEDIR=/var/run/$NAME 
test -x $DAEMON || exit 0 
case "$1" in 
  start)
    mkdir -p $PIDFILEDIR
    for conffilepath in $CONFDIR/*.json; do
        conffilename=$(basename $conffilepath)
        confname="${conffilename%.*}"
        specname="${NAME}-${confname}"
        PIDFILE=$PIDFILEDIR/$specname.pid
        echo -n "Starting $specname: " 
        $DAEMON -c "$conffilepath" 1> /var/log/$specname.log 2> /var/log/$specname.err.log & 
        echo $! > $PIDFILE 
        echo "$specname." 
    done
    ;; 
  stop)
    for pidfilepath in $PIDFILEDIR/*.pid; do
        pidfilename=$(basename $pidfilepath)
        pidname="${pidfilename%.*}"
        echo -n "Stopping $pidname: " 
        kill `cat $pidfilepath` 
        rm -f $pidfilepath 
        echo "$pidname." 
    done
    rm -rf $PIDFILEDIR
    ;; 
  restart|force-reload) 
    $0 stop 
    sleep 1 
    $0 start 
    ;; 
  *) 
    N=/etc/init.d/$NAME 
    echo "Usage: $N {start|stop|restart|force-reload}" >&2 
    exit 1 
    ;; 
esac 
exit 0
